spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:39.104.25.190}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:gwall}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info